console.log('Linea 1');
setTimeout(() => console.log('Linea 2'));
console.log('Linea 3');
setTimeout(() => console.log('Linea 4'), 1000);
console.log('Linea 5');
console.log('Linea 6');
setTimeout(() => console.log('Linea 7'), 500);
setTimeout(() => console.log('Linea 8'), 499);
console.log('Linea 9');
console.log('Linea 10');
console.log('Linea 11');
